language: java

jdk:
  - oraclejdk7
  - oraclejdk8

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - MAVEN_OPTS="-Xmx2G -XX:MaxPermSize=256m"

before_install: sudo rm /etc/mavenrc